<?php

use Longman\TelegramBot\Entities\BotCommand;
use Longman\TelegramBot\Entities\KeyboardButton;
use Longman\TelegramBot\Request;

class TelegramCommand extends xPDOSimpleObject
{
    /* @var TelegramBot|null $bot */
    protected $bot;

    /**
     * {@inheritdoc}
     */
    public function save($cacheFlag = null)
    {
        if ($this->isNew()) {
            if (empty($this->get('createdon'))) {
                $this->set('createdon', time());
            }
        } else {
            $this->set('updatedon', time());
        }
        return parent::save();
    }


    /**
     * @return TelegramBot|null
     */
    public function bot()
    {
        if (is_null($this->bot)) {
            /* @var TelegramBot $bot */
            $bot = $this->getOne('Bot');
            $this->bot = $bot;
        }
        return $this->bot;
    }

    public function getCommand()
    {
        return new BotCommand(
            [
                'command' => $this->get('command'),
                'description' => $this->get('description'),
            ]
        );
    }


    public function getKeyboardButton()
    {
        $KeyBoard = new KeyboardCommand([
            'text' => 'Жми'
        ]);
        return $KeyBoard;

    }

    public function install()
    {
        return $this->bot()->setMyCommands();
    }

    public function unInstall()
    {
        return $this->bot()->deleteMyCommands($this);
    }

    public function remove(array $ancestors = array())
    {

        $this->unInstall();
        return parent::remove($ancestors); // TODO: Change the autogenerated stub
    }
}
